### ISSUE TITLE
Getting error when running when running the script

### ISSUE THREAD

**Issue by thelastoth** [Netesfiu/EON-SPOOKER#1]
Under Ubuntu, when I'm trying to run python3 EON_SPOOKER.py, I got the following error ( prereqs already installed ): 

Traceback (most recent call last):
  File "/root/EON-SPOOKER/EON_SPOOKER.py", line 41, in <module>
    csv_file_path = select_csv_file()
  File "/root/EON-SPOOKER/EON_SPOOKER.py", line 8, in select_csv_file
    root = Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by Netesfiu** [comment]
Thank you for your feedback!

The error is might be related to that you used the script on a headless client (aka a machine with no delegated peripherials) and tkinter was unable to find any monitor in the enviroment.

Could you specify the hardware the OS is installed on and the way you interacted with the terminal?



> Under Ubuntu, when I'm trying to run python3 EON_SPOOKER.py, I got the following error ( prereqs already installed ):
> 
> Traceback (most recent call last): File "/root/EON-SPOOKER/EON_SPOOKER.py", line 41, in csv_file_path = select_csv_file() File "/root/EON-SPOOKER/EON_SPOOKER.py", line 8, in select_csv_file root = Tk() File "/usr/lib/python3.10/tkinter/**init**.py", line 2299, in **init** self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use) _tkinter.TclError: no display name and no $DISPLAY environment variable
